// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh5D6onJLM_4lwmo6XpjHSVVO3WfypCbA',
    appId: '1:86234724819:web:f5561e527c8576982bd726',
    messagingSenderId: '86234724819',
    projectId: 'gen-lang-client-0140675019',
    authDomain: 'gen-lang-client-0140675019.firebaseapp.com',
    storageBucket: 'gen-lang-client-0140675019.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuGwIrUmxLh-wqa6Lk4vyYvizrH7ZPVFY',
    appId: '1:86234724819:android:0628dbda02a7cab12bd726',
    messagingSenderId: '86234724819',
    projectId: 'gen-lang-client-0140675019',
    storageBucket: 'gen-lang-client-0140675019.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl-JBZStOw2D39HCMUt00xW_MpjcdkQc4',
    appId: '1:86234724819:ios:f2cee589ec0768d22bd726',
    messagingSenderId: '86234724819',
    projectId: 'gen-lang-client-0140675019',
    storageBucket: 'gen-lang-client-0140675019.firebasestorage.app',
    iosClientId: '86234724819-u6p3kqc4d1pps1bssdp3u2rfj1tm44np.apps.googleusercontent.com',
    iosBundleId: 'y',
  );
}
